// Generated from ../data/*.csv by scripts/generate-data.mjs.
// Do not edit this file by hand. Data itself lives in generated-data.json.
import data from "./generated-data.json";

export const venueData = data;
